language: objective-c
osx_image: xcode9
xcode_project: SplashBuddy.xcodeproj
xcode_scheme: SplashBuddy
xcode_sdk: macosx10.13
matrix:
  include:
  - xcode_sdk: macosx10.13
  - xcode_sdk: macosx10.12
script:
- set -o pipefail
- xcodebuild build test -project SplashBuddy.xcodeproj -scheme SplashBuddy
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications: 
slack: macadmins:Q5jgs97J5c9fqvubb1Kk301W
before_install:
- openssl aes-256-cbc -K $encrypted_280089750dac_key -iv $encrypted_280089750dac_iv
  -in Assets/Mac-Developer-20180109.p12.enc -out Assets/Mac-Developer-20180109.p12
  -d
- ./.travis.import_identity.sh
env:
  global:
    secure: FzKTuSMe7KHjDt/oYuSj4qyo6E+jPrVHbtpDjA/jCRTJHoapdY6LfEKSu6MvCUKZ7u5b3YqqJveIfbnPJnZDoMxLLfNd+SJfHCLlgnpmvgN4tFOrIbfbkHcqn2Ae3BGEzMTGg8fvDZQLMn5MlMM/5+oUWSHX9xGBsDW5g2USZnt7L8GmjuBoJ88fFono2btSTbQUDc159Ji0LBDlXmEvGXDiTWmAsCHXVQPGTVDDQ+EeFVBbm+n/FCKdrsRGRn03RXXFuphx6QHjFlgfSCBSQxPTjHXYUqrAAQXZw5igU6K4Xtc+c+dk/iWpbbx40g9LJCWxLRSSdGnu+uFthsgMqmdKqmqOL9k+EpuhA76cGrXLr4VNfhP+8aNd2roGhO/yFauoYS711TEA8M7zQ3oSYzgcdGWV0MF8g8AfQ4TMyZxSP2wDJ0ZpEyRtOeNAGEeE9yCMR8UNLVa6GE9MM70ToAg0p7e6Tcyp2uXepgZdHD1G/oI0Rg6oeltrgOb+/wD3nLN0ZKBd5fxXlX0mNH7Pr7rybhqu2jTDUGMZ2CehcL9OlRENHL81rZD5R2n5HZ20METs4ockpJt4dfKsj+ivGNw2TEiBuvVKdx2m2V5Yd+uA9pHFCI1Sc9VL6TN8OXOEBuoqMHNxNqYSepgudEA3iPsoGXeohaXU+ImnN/czR20=
